# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: widgetless

description: "Flutter Widget-less"

publish_to: 'none'

version: 0.0.1+1

#homepage: https://github.com/

#repository: https://github.com/

#issue_tracker: https://github.com/

#funding:
#  - https://www.buymeacoffee.com/
#  - https://www.patreon.com/
#  - https://boosty.to/

#topics:
#  -
#  -

#platforms:
#  android:
#  ios:
#  linux:
#  macos:
#  web:
#  windows:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png


# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

# https://dart.dev/tools/pub/workspaces
#workspace:
#  - packages/ui


#executables:
#  - tool/roadmap.dart


# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"


dependencies:
  flutter:
    sdk: flutter

  # Logger
  l: ^5.0.0

  # Annotation
  #json_annotation: ^4.9.0
  meta: any

  # Utility
  collection: any
  async: any
  path: any
  convert: any
  path_provider: ^2.1.4
  platform_info: ^5.0.0

  # Database
  #drift: ^2.23.0
  #sqlite3_flutter_libs: ^0.5.28

  # Networking
  #http: ^1.2.2
  #dio: ^5.4.2+1
  #dio_smart_retry: ^6.0.0


dev_dependencies:
  # Unit & Widget tests for Flutter
  flutter_test:
    sdk: flutter
  # Integration tests for Flutter
  integration_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0

  # Testing
  test: any

  # Code generation
  #build_runner: ^2.4.13
  #drift_dev: ^2.23.0
  #pubspec_generator: ^4.1.0-pre.1
  #flutter_gen_runner: ^5.8.0
  #json_serializable: ^6.8.0
  # dart run flutter_launcher_icons -f flutter_launcher_icons.yaml
  #flutter_launcher_icons: ^0.14.1
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  #flutter_native_splash: ^2.4.1


# ==============================================================================
# FLUTTER CONFIGURATION
# ==============================================================================

flutter:
  generate: false
  uses-material-design: false


#flutter_intl:
#  enabled: true
#  class_name: GeneratedLocalization
#  main_locale: en
#  arb_dir: lib/src/common/localization
#  output_dir: lib/src/common/localization/generated
#  use_deferred_loading: false


flutter_gen:
  output: lib/src/common/constant/
  line_length: 120
